language: go

go:
  - 1.13.x
  - tip

before_install:
  - go get -t -v ./...

go_import_path: github.com/andmorefine/go-coveralls/book

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
